Upgrade to Micronaut 3.0.0-M2
micronaut-projects/micronaut-flyway pull request #212
Opened 2021-06-22 14:21 UTC by ilopmar

Fixes #209

2021-07-15 11:11 UTC, sdelamo commented on flyway/build.gradle
> +    api "io.projectreactor:reactor-core"
this should be `implementation` instead of `api`

2021-07-15 11:13 UTC, sdelamo requested changes

2021-07-15 11:13 UTC, sdelamo commented on flyway/build.gradle
> +//    api "io.micronaut.reactor:micronaut-reactor"
delete this

2021-07-15 11:28 UTC, sdelamo approved these changes

2021-07-21 13:44 UTC, ilopmar commented
This module doesn't really need Micronaut 3 so I'll keep 2.5.9 but it is compatible with Micronaut 3.

2021-07-21 13:45 UTC, merged