Unable to configure flyway.datasources.*.ignore-migration-patterns
micronaut-projects/micronaut-flyway pull request #330
Opened 2022-08-02 09:40 UTC by timyates

Supersedes https://github.com/micronaut-projects/micronaut-flyway/pull/325 with a small test addition (also to get Sonar to run)

Fixes #309

2022-08-02 10:58 UTC, alvarosanchez approved these changes

2022-09-01 10:58 UTC, sdelamo requested changes

2022-09-01 10:58 UTC, sdelamo commented on flyway/src/main/java/io/micronaut/flyway/ValidatePatternTypeConverter.java
> +        if (pattern == null || pattern.trim().length() == 0) {
use `StringUtils.isEmpty(patterns)`

2022-09-01 10:59 UTC, sdelamo commented on flyway/src/main/java/io/micronaut/flyway/ValidatePatternTypeConverter.java
> +        if (pattern == null || pattern.trim().length() == 0) {
nevermind, `StringUtils::isEmpty` will not do the `trim`

2022-09-01 11:00 UTC, sdelamo approved these changes

2022-09-01 11:00 UTC, merged